"""empty message

Revision ID: 6a8abe16657a
Revises: dd8bdb792a69
Create Date: 2024-04-04 18:26:57.154377

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6a8abe16657a'
down_revision = 'dd8bdb792a69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_image', sa.String(length=150), nullable=True))
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('avatar_image')

    # ### end Alembic commands ###
