"""empty message

Revision ID: 945235fa7378
Revises: a618d592a2df
Create Date: 2024-04-05 12:31:31.092961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '945235fa7378'
down_revision = 'a618d592a2df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_image', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('cover_image_temporary', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('cover_image_temporary')
        batch_op.drop_column('cover_image')

    # ### end Alembic commands ###
